---
# tasks file for internal-port-connectivity-validator-postgres
- name: Postgres Qpid Mgmt port connectivity status
  wait_for:
    port: '{{ pg_int_mgmt_port }}'
    host: '{{ private_address }}'
    timeout: 1
  register: pg_int_mgmt_port_status
  ignore_errors: yes

- name: Postgres Data port connectivity status
  wait_for:
    port: '{{ pg_db_port }}'
    host: '{{ private_address }}'
    timeout: 1
  register: mp_router_port_status
  ignore_errors: yes

- name: Internal Postgres JMX port connectivity status
  wait_for:
    port: '{{ pg_jmx_port }}'
    host: '{{ private_address}}'
    timeout: 1
  register: pg_jmx_port_status
  ignore_errors: yes

- name: Postgres Mgmt port connectivity status
  wait_for:
    port: '{{ pg_ext_mgmt_port }}'
    host: '{{ private_address}}'
    timeout: 1
  register: pg_ext_mgmt_port_status
  ignore_errors: yes
